version: '3'
services:
  web:
    build: ./frontend/
    ports:
      - "3000:3000"
    working_dir: /usr/src/frontend
    depends_on:
      - api

  api:
    build: ./backend/
    ports:
      - "3001:3001"
    working_dir: /usr/src/backend
    depends_on:
      - ai
  
  ai:
    build: ./IA/chatgpt-retrieval/
    ports:
      - "5000:5000"
    working_dir: /app
